<?php

namespace App\Repository;

use App\Entity\Book;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function add(Book $entity, bool $flush = false): void
    {
        $this->getEntityManager()->persist($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    public function findByTitle(string $title): ?Book
    {
        return $this->findOneBy(['title' => $title]);
    }

    public function findById(string $id): ?Book
    {
        return $this->findOneBy(['id' => $id]);
    }

    public function delete(Book $entity, bool $flush = false): void
    {
        $this->getEntityManager()->remove($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    public function deleteById(int $id)
    {
        return $this->createQueryBuilder('b')
            ->delete('books', 'b')
            ->where('b.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->execute();
    }
}
