<?php

namespace App\Repository;

use App\Entity\UserIdentity;

/**
 * UserIdentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserIdentityRepository extends \Doctrine\ORM\EntityRepository
{
    public function add(UserIdentity $entity, bool $flush = false): void
    {
        $this->getEntityManager()->persist($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    public function findOneByLoginField($value): ?UserIdentity
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.login = :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }

    public function findOneByToken($value): ?UserIdentity
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.token = :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
