<?php

namespace App\Repository;

use App\Entity\WaitingItem;

/**
 * WaitingItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaitingItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function add(WaitingItem $entity, bool $flush = false): void
    {
        $this->getEntityManager()->persist($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    public function findByBookId(int $bookId): ?WaitingItem
    {
        return $this->findOneBy(['bookId' => $bookId]);
    }

    public function findByUserId(int $bookId): ?WaitingItem
    {
        return $this->findOneBy(['bookId' => $bookId]);
    }

    public function getNextByBookId( int $bookId): ?WaitingItem
    {
        return $this->findOneBy(['bookId' => $bookId], ['dateCreated' => 'desc']);
    }

    public function delete(WaitingItem $entity, bool $flush = false): void
    {
        $this->getEntityManager()->remove($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }


}
