<?php

namespace App\Repository;

use App\Entity\WaitingItem;

/**
 * WaitingItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaitingItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function add(WaitingItem $entity, bool $flush = false): void
    {
        $this->getEntityManager()->persist($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }
}
